name: 'gie_european_gas_storage'
version: '0.1'
config-version: 2

profile: 'gie'

require-dbt-version: [">=1.0.0", "<2.0.0"]

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
log-path: "logs"
packages-install-path: "dbt_packages"
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  materialized: table
  gie:
    # Config indicated by + and applies to all files under models/example/
    materialized: table
    example:
      +materialized: view

  jaffle_shop:
      materialized: table
      staging:
        materialized: view
