version: 2

sources:
  - name: gie_stage
    # database: main
    # schema: stage_gas
    schema: landing
    loader: dlt pipeline.
    description: "Raw gas storage and in/outlfow data for EU countries provided by GIE (https://agsi.gie.eu/)."
    freshness:
      warn_after: {count: 12, period: hour}
      #error_after: {count: 24, period: hour}
    #loaded_at_field: _sdc_extracted_at
    tables:
      - name: storage
        description: Source data at EU/non-EU level.
      - name: storage__children
        description: Source data at country level.
      - name: storage__children__children
        description: Source data at company level.
      - name: storage__children__children__children
        description: Source data at SSO/storage facility level.
      - name: _load_info
        description: Load info for dlt jobs
      - name: _load_info__loads_ids
        description: Additional load info for dlt jobs