# https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles
config:
  send_anonymous_usage_stats: False
  use_colors: True
gei:
  #target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"
  target: "dev"
  outputs:
    dev:
      type: duckdb
      #path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      path: "/workspaces/mimosa/gas_storage.duckdb"
      schema: gas_storage
      database: main
      threads: 2
      #threads: 1
      #schema: main
    test:
      type: duckdb
      #path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      path: "/project/data/test/data.duckdb"
      threads: 4
    prod:
      type: duckdb
      #path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      path: "/workspaces/mimosa/gas_storage.duckdb"
      threads: 4